openapi: 3.0.3
info:
  title: XRPL Test Project
  version: 1.1.0
servers:
  - url: http://localhost:1337
paths:
  /api/assets/:
    get:
      operationId: All currencies that stored in DB
      parameters:
      - in: query
        name: currency
        schema:
          type: string
      - in: query
        name: currency__contains
        schema:
          type: string
      - in: query
        name: issuer
        schema:
          type: string
      - in: query
        name: issuer__contains
        schema:
          type: string
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - assets
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedAssetInfoList'
          description: ''
  /api/payments/:
    get:
      operationId: Get all payments from DB
      parameters:
      - in: query
        name: account
        description: Exact match by source account of payment transaction
        schema:
          type: string
      - in: query
        name: account__contains
        description: Case-sensitive containment match
        schema:
          type: string
      - in: query
        name: amount
        description: Exact match by value of payment transaction
        schema:
          type: string
      - in: query
        name: currency
        description: Exact match by currency code
        schema:
          type: string
      - in: query
        name: currency__contains
        description: Case-sensitive containment match
        schema:
          type: string
      - in: query
        name: destination
        description: Exact match by target payment transaction account
        schema:
          type: string
      - in: query
        name: destination__contains
        description: Case-sensitive containment match
        schema:
          type: string
      - in: query
        name: destination_tag
        description: Exact match
        schema:
          type: integer
      - in: query
        name: destination_tag__isnull
        schema:
          type: boolean
      - in: query
        name: hash
        description: Exact match by hash of payment transaction
        schema:
          type: string
      - in: query
        name: hash__contains
        schema:
          type: string
      - in: query
        name: issuer
        description: Exact match by currency code issuer (also an account)
        schema:
          type: string
      - in: query
        name: issuer__contains
        description: Case-sensitive containment match
        schema:
          type: string
      - in: query
        name: ledger_idx
        description: Exact match by ledger index
        schema:
          type: integer
      - in: query
        name: ledger_idx__gt
        description: Greater than
        schema:
          type: integer
      - in: query
        name: ledger_idx__gte
        description: Greater than or equal to
        schema:
          type: integer
      - in: query
        name: ledger_idx__lt
        description: Less than
        schema:
          type: integer
      - in: query
        name: ledger_idx__lte
        description: Less than or equal to
        schema:
          type: integer
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - payments
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedListPaymentList'
          description: ''
    post:
      operationId: Request account payments to store them in DB
      tags:
      - payments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestLastPayments'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RequestLastPayments'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RequestLastPayments'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestLastPayments'
          description: ''
  /api/payments/{hash}/:
    get:
      operationId: Get payment from DB by payment hash
      parameters:
      - in: path
        name: hash
        schema:
          type: string
        description: A unique value identifying this Payment Transaction.
        required: true
      tags:
      - payments
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPayment'
          description: ''
  /api/xrpl-accounts/:
    get:
      operationId: Get XRPL accounts list
      parameters:
      - in: query
        name: hash
        schema:
          type: string
      - in: query
        name: hash__contains
        schema:
          type: string
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - xrpl-accounts
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedXRPLAccountList'
          description: ''
  /api/xrpl-accounts/{hash}/:
    get:
      operationId: Get XRPL account by account id
      parameters:
      - in: path
        name: hash
        schema:
          type: string
        description: A unique value identifying this XRPL Account.
        required: true
      tags:
      - xrpl-accounts
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XRPLAccount'
          description: ''
components:
  schemas:
    AssetInfo:
      type: object
      properties:
        issuer:
          type: string
          description: Currency code issuer
          maxLength: 35
          readOnly: true
        currency:
          type: string
          description: Currency code
          default: XRP drops
          maxLength: 40
          readOnly: true
      required:
      - currency
      - issuer
    Currency:
      type: object
      properties:
        name:
          type: string
          readOnly: true
      required:
      - name
    ListPayment:
      type: object
      properties:
        hash:
          type: string
          description: Unique payment transaction ID
          maxLength: 64
          readOnly: true
        account:
          type: string
          description: Source account of transaction
          maxLength: 35
          readOnly: true
        destination:
          type: string
          description: Target account of transaction
          maxLength: 35
          readOnly: true
        asset_info:
          $ref: '#/components/schemas/AssetInfo'
        ledger_idx:
          type: integer
          readOnly: true
        destination_tag:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
          readOnly: true
          nullable: true
        amount:
          description: Value of payment transaction
          example: "12345"
          type: string
          maxLength: 24
          readOnly: true
        fee:
          example: "12345"
          description: Transaction cost
          type: string
          readOnly: true
          maxLength: 24
      required:
      - account
      - amount
      - asset_info
      - destination
      - destination_tag
      - fee
      - hash
      - ledger_idx
    PaginatedAssetInfoList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/AssetInfo'
    PaginatedListPaymentList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/ListPayment'
    PaginatedXRPLAccountList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/XRPLAccount'
    RequestLastPayments:
      type: object
      properties:
        url:
          type: string
          description: XRPL server address
          format: uri
        account:
          type: string
          description: ID of target account to store its payments
          maxLength: 35
      required:
      - account
      - url
    XRPLAccount:
      type: object
      properties:
        hash:
          type: string
          readOnly: true
      required:
      - hash
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
