# Generated by Django 4.1.5 on 2023-01-10 04:19

import django.db.models.deletion
from django.db import migrations, models

import xrpl_app.models
import xrpl_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Info",
                "verbose_name_plural": "Assets Info",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "name",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="XRPLAccount",
            fields=[
                (
                    "hash",
                    models.CharField(max_length=35, primary_key=True, serialize=False),
                ),
            ],
            options={
                "verbose_name": "XRPL Account",
                "verbose_name_plural": "XRPL Accounts",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("ledger_idx", models.PositiveBigIntegerField()),
                ("destination_tag", models.PositiveBigIntegerField(null=True)),
                (
                    "hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "amount",
                    models.CharField(
                        max_length=24, validators=[xrpl_app.validators.validate_numeric]
                    ),
                ),
                (
                    "fee",
                    models.CharField(
                        max_length=24, validators=[xrpl_app.validators.validate_numeric]
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="xrpl_app.xrplaccount",
                    ),
                ),
                (
                    "asset_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_info",
                        to="xrpl_app.assetinfo",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination",
                        to="xrpl_app.xrplaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
            },
        ),
        migrations.AddField(
            model_name="assetinfo",
            name="currency",
            field=models.ForeignKey(
                default=xrpl_app.models.Currency.get_default_currency,
                on_delete=django.db.models.deletion.CASCADE,
                to="xrpl_app.currency",
            ),
        ),
        migrations.AddField(
            model_name="assetinfo",
            name="issuer",
            field=models.ForeignKey(
                default=xrpl_app.models.XRPLAccount.get_default_account,
                on_delete=django.db.models.deletion.CASCADE,
                to="xrpl_app.xrplaccount",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetinfo",
            constraint=models.UniqueConstraint(
                fields=("issuer", "currency"), name="unique_asset_issuer_currency"
            ),
        ),
    ]
